included:
  - Sources

excluded:
  - Tests

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - conditional_returns_on_newline
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - redundant_nil_coalescing
  - sorted_imports
  - static_operator
  - empty_xctest_method
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

analyzer_rules:
  - unused_declaration
  - unused_import

vertical_whitespace:
  max_empty_lines: 2

function_body_length: 250

cyclomatic_complexity:
  warning: 3 # Two nested ifs are acceptable
  error: 4   # 4 nested ifs shows warning, 5 causes compile error

type_body_length: 400

file_length: 1000

line_length:
  error: 200
  ignores_function_declarations: true

reporter: "json"
