os: osx
osx_image: xcode11.4
language: swift
xcode_project: DVR.xcodeproj

matrix:
  include:
    - xcode_scheme: DVR-iOS
      xcode_sdk: iphonesimulator
      env:
        - DESTINATION="iOS Simulator,OS=12.2,name=iPhone X"
    - xcode_scheme: DVR-macOS
      xcode_sdk: macosx
      env:
        - DESTINATION="macOS,arch=x86_64"
    - xcode_scheme: DVR-tvOS
      xcode_sdk: appletvsimulator
      env:
        - DESTINATION="tvOS Simulator,name=Apple TV 4K,OS=12.2"
    - env:
      - SWIFT_BUILD=true

script:
  - ./Scripts/travis-build-test.sh
